baseURL               = "https://webstack-hugo-crx.pages.dev/"
languageCode          = "zh-CN"
title                 = "丙醛说 | 科学上网 | 机场推荐 | TikTok工具 | 建站教程 | VPS推荐 | 办公工具"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"


[params]
    author        = "Lewis Lee"
    description   = "丙醛说 | 科学上网 | 机场推荐 | TikTok工具 | 建站教程 | VPS推荐 | 办公工具"
    upload        = "https://hbqfkj.cn/contact/"
    about         = "https://hbqfkj.cn/warning/"
    repository    = "https://github.com/ch3ch2cho2021/WebStack-Hugo"
    enablePreLoad = true
    textPreLoad   = "丙醛说网址导航"
    expandSidebar = false
    logosPath     = "assets/images/logos"
    defaultLogo   = "assets/images/logos/default.webp"
    nightMode     = false
    yiyan         = false
    fancybox      = true

[params.seo]
    baiduhmid       = ''
    baiduSiteVer    = ''
    tj51laid        = ''
    tj51lack        = ''
    GoogleAdsClient = ''

[params.qweather]
    key = ""

[params.images]
    favicon           = "assets/images/bi-favicon.png"
    searchImageL      = "assets/images/bg-dna.jpg"
    searchImageD      = "assets/images/bg-dna.jpg"
    logoExpandLight   = "assets/images/bi-expand-dark.png"
    logoExpandDark    = "assets/images/bi-expand-light.png"
    logoCollapseLight = "assets/images/bi.png"
    logoCollapseDark  = "assets/images/bi.png"

[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = '本站内容源自互联网，如有内容侵犯了你的权益，请联系删除相关内容。<br/>&copy; 2024 - {year} By [丙醛说](https://hbqfkj.cn) | [免责声明](https://hbqfkj.cn/warning/) | [联系方式](mailto:emily24826@gmail.com) | [隐私政策](https://hbqfkj.cn/privacy-policy/)<br/>'
